# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grendel-ruby}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brad Greenlee"]
  s.date = %q{2010-04-29}
  s.description = %q{Grendel is a RESTful web service which allows for the secure storage of users'
    documents. Grendel-Ruby provides a Ruby API for Grendel.}
  s.email = %q{brad@wesabe.com}
  s.extra_rdoc_files = [
    "LICENSE.md",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE.md",
     "README.md",
     "Rakefile",
     "TODO.md",
     "VERSION",
     "grendel-ruby.gemspec",
     "lib/grendel.rb",
     "lib/grendel/client.rb",
     "lib/grendel/document.rb",
     "lib/grendel/document_manager.rb",
     "lib/grendel/link.rb",
     "lib/grendel/link_manager.rb",
     "lib/grendel/linked_document.rb",
     "lib/grendel/linked_document_manager.rb",
     "lib/grendel/mash.rb",
     "lib/grendel/user.rb",
     "lib/grendel/user_manager.rb",
     "spec/grendel/client_spec.rb",
     "spec/grendel/document_manager_spec.rb",
     "spec/grendel/document_spec.rb",
     "spec/grendel/link_manager_spec.rb",
     "spec/grendel/link_spec.rb",
     "spec/grendel/linked_document_manager_spec.rb",
     "spec/grendel/linked_document_spec.rb",
     "spec/grendel/user_manager_spec.rb",
     "spec/grendel/user_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/wesabe/grendel-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby interface to Wesabe's Grendel}
  s.test_files = [
    "spec/grendel/client_spec.rb",
     "spec/grendel/document_manager_spec.rb",
     "spec/grendel/document_spec.rb",
     "spec/grendel/link_manager_spec.rb",
     "spec/grendel/link_spec.rb",
     "spec/grendel/linked_document_manager_spec.rb",
     "spec/grendel/linked_document_spec.rb",
     "spec/grendel/user_manager_spec.rb",
     "spec/grendel/user_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 0"])
  end
end

